#-*- coding:utf-8 -*-
"""Subclass of Activ, which is generated by wxFormBuilder."""

import wx
from . import _gui  # @UnresolvedImport
import time
import libs

# Implementing Activ

class Activ(_gui.Activ):
    def __init__( self, parent ):
        _gui.Activ.__init__( self, parent )
        self.SetTitle(_(u'Активиране'))
        self.m_textCtrl1.SetLabel(_(u'БАЗОВ КОД'))
        self.m_textCtrl2.SetLabel(_(u'КОД ЗА АКТИВАЦИЯ'))

    # Handlers for Activ events.
    def OnClose( self, event ):
        self.Destroy()

    def OnActiv( self, event ):
        key = self.m_textCtrl2.GetValue()
        base = self.m_textCtrl1.GetValue()
        response = libs.udp.send('ACTIV', ip=libs.conf.JPSERVERIP, port=libs.conf.JPSERVERPORT, key=key, base=base)
        time.sleep(5)
        if response == True:
            wx.MessageBox(_(u'Успешна активация. Рестартирайте програмата!'), 'Info',
                                wx.OK | wx.ICON_INFORMATION)
            self.Destroy()
        else:
            wx.MessageBox(_(u'Грешен код за активация!'), 'Error', wx.OK | wx.ICON_ERROR)
            self.m_textCtrl1.SetValue(str(response))
            self.Layout()


    def OnHelp( self, event ):
        if libs.conf.DOCS_DEBUG == False:
            frame = libs.helps.Help(r'%s%s/colibri/v%s/jackpot.html' % (libs.conf.DOCS, libs.conf.USE_LANGUAGE, libs.conf.VERSION))
        else:
            frame = libs.helps.Help('http://127.0.0.1:5000/%s/colibri/v%s/jackpot.html' % (libs.conf.USE_LANGUAGE, libs.conf.VERSION))
